apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authservice-db-claim
  namespace: klusvoorjou
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
