apiVersion: v1
kind: Service
metadata:
  name: authservice-db-service
  namespace: klusvoorjou
spec:
  selector:
    app: authservice-db-pod
  ports:
  - port: 5201
    targetPort: 3306
  type: LoadBalancer
