apiVersion: apps/v1
kind: Deployment
metadata:
  name: authservice-deployment
  namespace: klusvoorjou
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authservice-pod
  template:
    metadata:
      labels:
        app: authservice-pod
    spec:
      containers:
      - name: authservice-container
        image: youris30/kvj_authservice
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        - containerPort: 443

