apiVersion: v1
kind: Service
metadata:
  name: authservice-service
  namespace: klusvoorjou
spec:
  selector:
    app: authservice-pod
  ports:
  - name: "http"
    port: 5025
    targetPort: 80
  - name: "https"
    port: 5024
    targetPort: 443
  type: LoadBalancer
